# change project directory: 
# cd "/Users/nikhilshah/Desktop/R Files/R Working Directory/nikhilshah7.github.io"

project:
  type: website
  output-dir: docs

website:
  title: "Nikhil Shah"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Data Sci Projects
        menu:
        - text: Data Viz (Lichess.org)
          href: dataviz1.qmd
        - text: Data Viz (National Park Species)
          href: dataviz2.qmd
        - text: Data Viz (Species Interactive App)
          href: dataviz3.qmd
        - text: Text Analysis (Palindromes)
          href: textanalysis.qmd
        - text: Simulation (Reverse 3-0 Odds)
          href: simulation.qmd
        - text: Data Science Ethics (Biased Hiring Algorithm)
          href: ethics.qmd
        - text: SQL (Hungry Cop Effect)
          href: sql.qmd
      - text: Presentation
        href: presentation.qmd
          

format:
  html:
    theme: 
      light: pulse
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: source

