# change project directory: 
# cd "/Users/nikhilshah/Desktop/R Files/R Working Directory/nikhilshah7.github.io"

project:
  type: website
  output-dir: docs

website:
  title: "Nikhil Shah"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Photography
        menu:
        - text: Milky Way
          href: milkyway.html
        - text: Wildlife
          href: wildlife.html
      - text: Data Science
        menu:
        - text: Riverside Warehouses
          href: https://radicalresearch.shinyapps.io/Socioeconomic/
        - text: IQAir
          href: https://github.com/nikhilshah7/RRC_IQAir
      - text: Articles
        menu:
        - text: 'BACUTI: Climate Disclosures (TBA)'
        - text: 'FSI: Lithium Extraction in South America (TBA)'
          

format:
  html:
    theme: 
      light: pulse
      dark: solar
    css: styles.css
    toc: true
    page-layout: full
    output-dir: docs
    prefer-html: true

editor: source

