# change project directory: 
# cd "/Users/nikhilshah/Desktop/R Files/R Working Directory/nikhilshah7.github.io"

project:
  type: website
  output-dir: docs

website:
  title: "Nikhil Shah"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Data Viz
        menu:
        - text: Lichess.org
          href: tuesday1.qmd
        - text: National Park Species
          href: tuesday2.qmd
      - href: project2.qmd
        text: Full Text Analysis (Palindromes)
      - href: project3.qmd
        text: Simulation Study (Reverse 3-0 Odds)
      - href: project4.qmd
        text: Data Science Ethics (Biased Hiring Algorithm)

format:
  html:
    theme: 
      light: pulse
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

