---
title: "National Park Species (Interactive)"
description: |
  Analysis of species in the most visited US national parks from TidyTuesday
author: Nikhil Shah
date: February 19, 2025
format: html
execute:
  shiny: true
runtime: shiny
---

```{r}
#| warning: false
#| message: false

library(tidyverse)

species <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2024/2024-10-08/most_visited_nps_species_data.csv')

animals <- species |>
  filter(CategoryName == 'Mammal' | CategoryName == 'Fish' | CategoryName == 'Bird' | CategoryName == 'Amphibian' | CategoryName == 'Reptile')

species <- species |>
  mutate(ParkName = str_replace(ParkName, ' National Park', '')) |>
  mutate(ParkName = fct_infreq(ParkName))

```


```{r}
#| warning: false
#| message: false

library(shiny)

ui <- fluidPage(
  fluidRow(
    column(6,
           selectInput("family", "Family:", 
                       choices = sort(unique(animals$Family)),
                       selected = "Mustelidae")
    ),
    column(6,
           textOutput('sample')
    )
  ),
  
  plotOutput("shinyplot")
)

server <- function(input, output, session) {
  
  output$shinyplot <- renderPlot({
    species |>
      filter(Family == input$family) |>
      ggplot(aes(y = ParkName)) +
      geom_bar(fill = '#003f00') +
      labs(
        y = 'National Park',
        x = '# Species',
        title = paste('Distinct species in family', input$family, 'in most popular national parks')
      ) +
      theme_minimal()
  })
  
  output$sample <- renderText({
    family_species <- species |>
      filter(Family == input$family)
    
    paste('Example species:', sample(family_species$CommonNames, 1))
  })
  
}

shinyApp(ui = ui, server = server)

```

https://nikhilshah.shinyapps.io/species/